import { Product } from "./types";

export const PRODUCTS: Product[] = [
  {
    id: "prod-tokyo-street-knit",
    name: "Tokyo Street Knit Hoodie",
    price: 110,
    originalPrice: 130,
    sizes: ["S", "M", "L", "XL", "XXL"],
    images: ["/19-10-2023-JWx_192BT232050F_1_1.webp"],
    description: "Embrace the Tokyo underground aesthetic with this premium heavy knit cotton hoodie, custom designed with raw slouchy styling and a double-lined structured hood.",
    colors: ["Black", "Coal Gray"],
    stock: 25,
    slug: "tokyo-street-knit-hoodie",
    tags: ["Youthful", "Streetwear", "Tokyo", "Heavyweight"],
    featured: true,
    category: "Hoodies",
    rating: 4.8,
    reviewsCount: 42,
    badge: "NEW IN"
  },
  {
    id: "prod-acid-wash-graphic",
    name: "Acid Wash Graphic Hoodie",
    price: 115,
    originalPrice: 140,
    sizes: ["S", "M", "L", "XL", "XXL"],
    images: ["/27656823_57543680_600.webp"],
    description: "Features custom chemical vintage dye patterns with bold neo-expressionist back-graphics. Perfect for expressive urban styles and comfortable daily fits.",
    colors: ["Sand", "Earth Brown"],
    stock: 18,
    slug: "acid-wash-graphic-hoodie",
    tags: ["Acid-Wash", "Graphic", "Vintage", "Oversized"],
    featured: true,
    category: "Hoodies",
    rating: 4.7,
    reviewsCount: 29,
    badge: "TRENDING"
  },
  {
    id: "prod-urban-rebel-heavyweight",
    name: "Urban Rebel Heavyweight Hoodie",
    price: 125,
    sizes: ["S", "M", "L", "XL", "XXL"],
    images: ["/5299061-30-2.jpg"],
    description: "Designed for ultimate durability and thick structures. Created with high-density cotton fleece, heavy ribbed cuffs, and custom metal drawstring caps.",
    colors: ["Beige", "Vintage Cream"],
    stock: 32,
    slug: "urban-rebel-heavyweight-hoodie",
    tags: ["Heavyweight", "Minimalist", "Cozy", "Streetwear"],
    featured: true,
    category: "Hoodies",
    rating: 4.9,
    reviewsCount: 56,
    badge: "BEST SELLER"
  },
  {
    id: "prod-chrome-minimalist-fleece",
    name: "Chrome Minimalist Fleece Hood",
    price: 135,
    originalPrice: 155,
    sizes: ["S", "M", "L", "XL", "XXL"],
    images: ["/Chrome-ProductPhotosShopify-2_55d55dac-350c-491f-8b78-602bfaec3657.webp"],
    description: "A super soft, brushed fleece hoodie highlighting clean seam lines and zero visible branding for a sleek, contemporary high-street look.",
    colors: ["Chrome Off-White", "Ice Silver"],
    stock: 14,
    slug: "chrome-minimalist-fleece-hood",
    tags: ["Fleece", "Minimalist", "Premium", "Clean"],
    featured: true,
    category: "Hoodies",
    rating: 4.6,
    reviewsCount: 38,
    badge: "STAFF PICK"
  },
  {
    id: "prod-archival-classic-fit",
    name: "Archival Classic Fit Hoodie",
    price: 95,
    sizes: ["S", "M", "L", "XL", "XXL"],
    images: ["/Hoodie.jpg"],
    description: "Our signature silhouette. Timeless classic hoodie silhouette in a thick knitted cotton blend with ultra-soft lining and a spacious pocket.",
    colors: ["Navy Blue", "Deep Indigo"],
    stock: 45,
    slug: "archival-classic-fit-hoodie",
    tags: ["Classic-Fit", "Essential", "Organic", "Warm"],
    featured: false,
    category: "Hoodies",
    rating: 4.5,
    reviewsCount: 88
  },
  {
    id: "prod-vintage-distressed-indigo",
    name: "Vintage Distressed Indigo Hoodie",
    price: 140,
    sizes: ["S", "M", "L", "XL", "XXL"],
    images: ["/J5-5108.jpg"],
    description: "Specially distressed with hand-grinded cuffs and faded seams for a naturally worn, raw vintage appeal. High-end Japanese loopback fabric.",
    colors: ["Indigo Wash", "Slate Blue"],
    stock: 12,
    slug: "vintage-distressed-indigo-hoodie",
    tags: ["Distressed", "Vintage", "Premium", "Indigo"],
    featured: true,
    category: "Hoodies",
    rating: 5.0,
    reviewsCount: 17,
    badge: "LIMITED"
  },
  {
    id: "prod-candyfloss-pink-college",
    name: "Candyfloss Pink College Hoodie",
    price: 85,
    sizes: ["S", "M", "L", "XL"],
    images: ["/JH001-AWDis-College-Unisex-Hoodie-Front-Candyfloss-Pink-Mens.webp"],
    description: "An eye-catching, vibrant pastel candyfloss pink shade crafted in a regular comfy unisex fit. Highly popular for collegiate and layering casual styles.",
    colors: ["Candyfloss Pink"],
    stock: 50,
    slug: "candyfloss-pink-college-hoodie",
    tags: ["Pastel", "Unisex", "Collegiate", "Bright"],
    featured: false,
    category: "Hoodies",
    rating: 4.4,
    reviewsCount: 65,
    badge: "POPULAR"
  },
  {
    id: "prod-kic-slouchy-grey",
    name: "KIC Slouchy Drop-Shoulder Hoodie",
    price: 120,
    originalPrice: 145,
    sizes: ["S", "M", "L", "XL", "XXL"],
    images: ["/KIC_322-6136-00738-900_model1.avif"],
    description: "High-grade architectural drape designed with dropped shoulders, heavyweight ribbing, and soft interior brushwork for ultimate daily relaxation.",
    colors: ["Light Heather Grey", "Charcoal"],
    stock: 22,
    slug: "kic-slouchy-drop-shoulder-hoodie",
    tags: ["Slouchy", "Drop-Shoulder", "Premium", "Grey"],
    featured: true,
    category: "Hoodies",
    rating: 4.9,
    reviewsCount: 47,
    badge: "COZY"
  },
  {
    id: "prod-metro-tech-charcoal",
    name: "Metro Tech-Fleece Utility Hoodie",
    price: 130,
    sizes: ["S", "M", "L", "XL", "XXL"],
    images: ["/X0568_SQ1_0000000005_GREY_MDf.jpg"],
    description: "Designed for urban tech activewear, featuring double-weave poly-cotton dynamic panels that ensure high heat insulation and water-resistant property.",
    colors: ["Tech Charcoal Grey", "Matte Black"],
    stock: 30,
    slug: "metro-tech-fleece-utility-hoodie",
    tags: ["Technical", "Utility", "Activewear", "Charcoal"],
    featured: false,
    category: "Hoodies",
    rating: 4.6,
    reviewsCount: 31
  },
  {
    id: "prod-washed-sage-fleece",
    name: "Washed Sage Fleece Hoodie",
    price: 105,
    sizes: ["S", "M", "L", "XL"],
    images: ["/a623522cc979422d9d06677ef93d7ab6.webp"],
    description: "A calming pastel sage green wash processed with safe stone extraction wash for beautiful faded edges and absolute plush comfort.",
    colors: ["Washed Sage", "Alabaster"],
    stock: 20,
    slug: "washed-sage-fleece-hoodie",
    tags: ["Sage-Green", "Stone-Wash", "Fleece"],
    featured: false,
    category: "Hoodies",
    rating: 4.7,
    reviewsCount: 22
  },
  {
    id: "prod-alabaster-slouchy-oversized",
    name: "Alabaster Slouchy Oversized Hoodie",
    price: 118,
    sizes: ["S", "M", "L", "XL", "XXL"],
    images: ["/c8b2006163cd08e3c1fdab7e2d2bde8171ce790e.avif"],
    description: "Brighten your wardrobe with this highly refined cloud-white oversized luxury hoodie. Crafted from 480gsm organic heavyweight French Terry cotton.",
    colors: ["Alabaster White", "Oatmeal Cream"],
    stock: 28,
    slug: "alabaster-slouchy-oversized-hoodie",
    tags: ["Oversized", "Luxury", "French-Terry", "White"],
    featured: true,
    category: "Hoodies",
    rating: 4.9,
    reviewsCount: 35,
    badge: "PREMIUM"
  },
  {
    id: "prod-cyber-city-neo-gothic",
    name: "Cyber-City Neo-Gothic Hood",
    price: 145,
    originalPrice: 160,
    sizes: ["S", "M", "L", "XL", "XXL"],
    images: ["/dac12d317e4fad45eb0069b3207f3d4b.webp"],
    description: "Bold gothic typeface embroidery covers the back/arms. A heavy outer garment inspired by night streetscapes, built with maximum styling protection.",
    colors: ["Cyber Slate", "Neon Violet"],
    stock: 16,
    slug: "cyber-city-neo-gothic-hood",
    tags: ["Gothic", "Cyberpunk", "Reflective", "Embroidery"],
    featured: false,
    category: "Hoodies",
    rating: 4.8,
    reviewsCount: 19
  },
  {
    id: "prod-high-street-graffiti-art",
    name: "High-Street Graffiti Art Hoodie",
    price: 138,
    sizes: ["S", "M", "L", "XL"],
    images: ["/streetwear-hoodie-2.webp"],
    description: "Features elaborate, bright graffiti spray calligraphy on premium heavy loopback material for a highly authentic alternative look.",
    colors: ["Dusty Sand", "Graffiti White"],
    stock: 15,
    slug: "high-street-graffiti-art-hoodie",
    tags: ["Graffiti", "High-Street", "Graphic", "Artistic"],
    featured: false,
    category: "Hoodies",
    rating: 4.7,
    reviewsCount: 26,
    badge: "HOT"
  },
  {
    id: "prod-athleta-sport-hybrid",
    name: "Athleta Sport Hybrid Track Hoodie",
    price: 148,
    originalPrice: 165,
    sizes: ["S", "M", "L", "XL", "XXL"],
    images: ["/whm250110-digital-ecomm-hoodies-athleta-4722-68f130c68943b.avif"],
    description: "Technical hybrid construction pairing warmth from dense sports interlock fabrics and high ventilation for all-day thermal equilibrium.",
    colors: ["Forest Green", "Pitch Black"],
    stock: 24,
    slug: "athleta-sport-hybrid-track-hoodie",
    tags: ["Athletic", "Hybrid", "High-Performance", "Track"],
    featured: true,
    category: "Hoodies",
    rating: 4.9,
    reviewsCount: 52,
    badge: "EXCLUSIVE"
  },
  {
    id: "prod-aesthetic-grey-model",
    name: "Aesthetic Grey Model Hoodie",
    price: 122,
    sizes: ["S", "M", "L", "XL", "XXL"],
    images: ["/-473Wx593H-700417694-grey-MODEL.avif"],
    description: "The gold standard of urban modeling hoodies. Premium grey luxury drape pairing perfectly with active trousers or loose cargo denim.",
    colors: ["Dust Grey", "Heather Black"],
    stock: 40,
    slug: "aesthetic-grey-model-hoodie",
    tags: ["Youthful", "Clean-Cut", "Grey-Model", "Warm"],
    featured: false,
    category: "Hoodies",
    rating: 4.8,
    reviewsCount: 74
  },
  {
    id: "prod-ts-classic-black",
    name: "Elsewhere Signature Logo Tee",
    price: 45,
    sizes: ["S", "M", "L", "XL"],
    images: ["/t-shirt/01404732400-p.webp"],
    description: "Our essential lightweight cotton crewneck, featuring the classic Signature logo embroidered on the chest. Perfectly suited for layering or standalone statement wear.",
    colors: ["Vintage Black", "Shadow Grey"],
    stock: 40,
    slug: "elsewhere-signature-logo-tee",
    tags: ["Essential", "Logo", "Organic-Cotton", "Signature"],
    featured: true,
    category: "T-shirts",
    rating: 4.8,
    reviewsCount: 30,
    badge: "ESSENTIAL"
  },
  {
    id: "prod-ts-varsity-green",
    name: "Varsity Green Graphic Tee",
    price: 50,
    originalPrice: 65,
    sizes: ["S", "M", "L", "XL"],
    images: ["/t-shirt/135271203-1-Varsity_20_20T_20_20-_20_20Shirts_20_20-_20_20Green_20_20-_20_20Small.webp"],
    description: "A collegiate-inspired streetwear top cut from premium medium-weight cotton. Highlights distressed athletic lettering and green-cream contrast block colors.",
    colors: ["Varsity Green", "Cream"],
    stock: 25,
    slug: "varsity-green-graphic-tee",
    tags: ["Collegiate", "Graphic", "Athletic", "Vintage"],
    featured: true,
    category: "T-shirts",
    rating: 4.7,
    reviewsCount: 22,
    badge: "TRENDING"
  },
  {
    id: "prod-ts-retro-print",
    name: "Retro Slouchy Print Tee",
    price: 48,
    sizes: ["S", "M", "L", "XL", "XXL"],
    images: ["/t-shirt/1_f318c0ca-ea45-4406-8bd0-ce74bd12e64d.webp"],
    description: "Featuring vintage chemical distress work and retro block prints on high-density Japanese loopweave fabric. Offers a premium structural drop and breathable daily performance.",
    colors: ["Off-White", "Washed Charcoal"],
    stock: 18,
    slug: "retro-slouchy-print-tee",
    tags: ["Retro", "Drop-Shoulder", "Distressed"],
    featured: false,
    category: "T-shirts",
    rating: 4.6,
    reviewsCount: 15
  },
  {
    id: "prod-ts-heavyweight-cream",
    name: "Heavyweight Slub Cotton Tee",
    price: 55,
    sizes: ["S", "M", "L", "XL", "XXL"],
    images: ["/t-shirt/35951169716-a4.jpg"],
    description: "Made of architectural 320gsm premium organic cotton with rough slub fabrics for rich surface texture. Heavy ribbed mockneck collar that retains shape perfectly.",
    colors: ["Vintage Cream", "Sand"],
    stock: 35,
    slug: "heavyweight-slub-cotton-tee",
    tags: ["Heavyweight", "Minimalist", "Mockneck", "Premium"],
    featured: true,
    category: "T-shirts",
    rating: 4.9,
    reviewsCount: 45,
    badge: "BEST SELLER"
  },
  {
    id: "prod-ts-retro-arcade",
    name: "Retro Arcade Oversized Tee",
    price: 42,
    originalPrice: 55,
    sizes: ["S", "M", "L", "XL"],
    images: ["/t-shirt/54_1.webp"],
    description: "Add retro streetwear nostalgia with this oversized computer design back-graphic tee. Soft-touch breathable fabric styled for cozy active movements.",
    colors: ["Slate Blue", "Pitch Black"],
    stock: 20,
    slug: "retro-arcade-oversized-tee",
    tags: ["Graphic", "Retro", "Oversized", "Arcade"],
    featured: false,
    category: "T-shirts",
    rating: 4.5,
    reviewsCount: 19,
    badge: "SALE"
  },
  {
    id: "prod-ts-aybl-sport",
    name: "AYBL Sport Training Tee",
    price: 52,
    sizes: ["S", "M", "L", "XL", "XXL"],
    images: ["/t-shirt/AYBL_AUG_MENS_20240368.webp"],
    description: "High-performance athletic layout combining premium light mesh weave with high sweat-wicking abilities for standard training or active street styles.",
    colors: ["Tech Grey", "Carbon Black"],
    stock: 30,
    slug: "aybl-sport-training-tee",
    tags: ["Athletic", "Training", "Activewear", "Breathable"],
    featured: false,
    category: "T-shirts",
    rating: 4.8,
    reviewsCount: 28
  },
  {
    id: "prod-ts-chemistry-graphic",
    name: "Chemistry Lab Expressionist Tee",
    price: 46,
    sizes: ["S", "M", "L", "XL"],
    images: ["/t-shirt/Chemistry.jpg"],
    description: "Unique hand-crafted scientific concept art graphic print on a relaxed lightweight combed cotton base, showcasing modern urban high-street artistic tones.",
    colors: ["Deep Navy", "White"],
    stock: 15,
    slug: "chemistry-lab-expressionist-tee",
    tags: ["Concept-Art", "Graphic", "Creative", "Soft-Touch"],
    featured: true,
    category: "T-shirts",
    rating: 4.9,
    reviewsCount: 14,
    badge: "CREATIVE"
  },
  {
    id: "prod-ts-minimalist-pocket",
    name: "Minimalist Utility Pocket Tee",
    price: 38,
    sizes: ["S", "M", "L", "XL", "XXL"],
    images: ["/t-shirt/Front_18347796-e718-4928-ab1d-05a6757bd2cd.webp"],
    description: "A versatile daily base layer fitted with an architectural drop pocket. Pre-shrunk cotton guarantees high dimensional stability over prolonged heavy washes.",
    colors: ["Slate Grey", "Olive Green"],
    stock: 48,
    slug: "minimalist-utility-pocket-tee",
    tags: ["Pocket", "Minimalist", "Essential", "Daily-Wear"],
    featured: false,
    category: "T-shirts",
    rating: 4.4,
    reviewsCount: 36
  },
  {
    id: "prod-ts-printed-oversize",
    name: "Oversize Cyber Back-Printed Tee",
    price: 58,
    originalPrice: 70,
    sizes: ["S", "M", "L", "XL", "XXL"],
    images: ["/t-shirt/Oversize_Back_Printed_oversize_t_shirt_for_men_-_FastColors_-_Oversize_Back_Printed_T-Shirt_-_FastColors_-_tag1_-_tag2_-_tag3_-_-6266647.webp"],
    description: "Features massive cyber typography design print on the upper back. Constructed from high-end heavy dry cotton, with relaxed dropped shoulders and raw silhouette lines.",
    colors: ["Jet Black", "Cyber Green"],
    stock: 12,
    slug: "oversize-cyber-back-printed-tee",
    tags: ["Backprint", "Cyberpunk", "Oversized", "Drop-Shoulder"],
    featured: true,
    category: "T-shirts",
    rating: 5.0,
    reviewsCount: 11,
    badge: "LIMITED"
  },
  {
    id: "prod-ts-avantgarde-drape",
    name: "Avant-Garde Drape Tee",
    price: 44,
    sizes: ["S", "M", "L", "XL"],
    images: ["/t-shirt/afb5a2a116463f0df214f907dd25a507.jpg"],
    description: "Masterfully structured lightweight summer tee, sporting a fluid aesthetic look and relaxed hemlines for ultimate layering styling combos.",
    colors: ["Melange Grey", "Classic White"],
    stock: 22,
    slug: "avant-garde-drape-tee",
    tags: ["Avant-Garde", "Fluid-Drape", "Lightweight", "Summer"],
    featured: false,
    category: "T-shirts",
    rating: 4.7,
    reviewsCount: 20
  },
  {
    id: "prod-pants-canvas-utility",
    name: "Elsewhere Utility Canvas Pants",
    price: 125,
    sizes: ["S", "M", "L", "XL", "XXL"],
    images: ["/pants/00016113-r5ziv9xc877t81y2b0077s2xi9fcdt8tzh6wfzk2lk.jpg"],
    description: "Structured daily utility trousers designed with multiple geometric work pockets, crafted from heavy-duty pre-shrunk cotton canvas.",
    colors: ["Off-White", "Cream"],
    stock: 25,
    slug: "elsewhere-utility-canvas-pants",
    tags: ["Utility", "Canvas", "Off-White", "Structured"],
    featured: true,
    category: "Pants",
    rating: 4.8,
    reviewsCount: 42,
    badge: "NEW IN"
  },
  {
    id: "prod-pants-slouchy-cargo",
    name: "Slouchy Loose-Fit Cargo Trousers",
    price: 135,
    sizes: ["S", "M", "L", "XL", "XXL"],
    images: ["/pants/00040156426-p.webp"],
    description: "Engineered with modern streetwear volume, featuring deep cargo side pockets and adjustable cord details for an absolute contemporary silhouette.",
    colors: ["Washed Grey", "Charcoal"],
    stock: 18,
    slug: "slouchy-loose-fit-cargo-trousers",
    tags: ["Cargo", "Loose-Fit", "Grey", "Streetwear"],
    featured: false,
    category: "Pants",
    rating: 4.7,
    reviewsCount: 29,
    badge: "TRENDING"
  },
  {
    id: "prod-pants-tawny-wide",
    name: "Classic Tawny Wide-Leg Trouser",
    price: 140,
    sizes: ["S", "M", "L", "XL", "XXL"],
    images: ["/pants/15_TheClassicTrouser_Tawny__41.webp"],
    description: "A premium flowing trouser colored in tawny brown tones, expertly tailored with double-front pleats and high-rise structures for luxury layering styles.",
    colors: ["Tawny Brown", "Sand"],
    stock: 14,
    slug: "classic-tawny-wide-leg-trouser",
    tags: ["Tailored", "Wide-Leg", "Classic", "Tawny"],
    featured: true,
    category: "Pants",
    rating: 4.9,
    reviewsCount: 38
  },
  {
    id: "prod-pants-knit-straight",
    name: "Relaxed Knit Straight Pants",
    price: 110,
    sizes: ["S", "M", "L", "XL", "XXL"],
    images: ["/pants/1_7e54aa70-0557-42f8-aee4-329b6b87072b.webp"],
    description: "Super soft combed loopback cotton blend trousers offering unmatched leisure comfort and a sleek straight drape for minimalist lounging.",
    colors: ["Cream White", "Oatmeal"],
    stock: 32,
    slug: "relaxed-knit-straight-pants",
    tags: ["Knit", "Straight", "Minimalist", "Cozy"],
    featured: false,
    category: "Pants",
    rating: 4.6,
    reviewsCount: 24
  },
  {
    id: "prod-pants-washed-denim",
    name: "Elsewhere Washed Denim Jeans",
    price: 145,
    sizes: ["S", "M", "L", "XL", "XXL"],
    images: ["/pants/35-7648097116328d0dbc17532951759225-1024-1024.webp"],
    description: "Constructed from thick raw-washed denim with fine distressed features, offering an avant-garde vintage texture and an accommodating relaxed thigh profile.",
    colors: ["Stone Blue", "Ink Indigo"],
    stock: 15,
    slug: "elsewhere-washed-denim-jeans",
    tags: ["Denim", "Distressed", "Raw-Wash", "Vintage"],
    featured: false,
    category: "Pants",
    rating: 4.5,
    reviewsCount: 19
  },
  {
    id: "prod-pants-urban-drape",
    name: "Minimal Urban Drape Pants",
    price: 120,
    sizes: ["S", "M", "L", "XL", "XXL"],
    images: ["/pants/7d0647bb75cc69d555e8af1dde0f58c9.webp"],
    description: "Designed to fall elegantly from the hips down, using specialized lightweight dynamic blends that block wind while retaining high breathability.",
    colors: ["Shadow Black", "Ink Gray"],
    stock: 22,
    slug: "minimal-urban-drape-pants",
    tags: ["Drape", "Windproof", "Minimalist", "Black"],
    featured: false,
    category: "Pants",
    rating: 4.7,
    reviewsCount: 21
  },
  {
    id: "prod-pants-tech-cargo",
    name: "Architectural Tech Cargo Pants",
    price: 150,
    sizes: ["S", "M", "L", "XL", "XXL"],
    images: ["/pants/Artboard83_5.webp"],
    description: "A futuristic athletic masterpiece compiled with technical hardware, asymmetric zipper overlays, and water-repellent shell textures.",
    colors: ["Matte Black", "Tech Olive"],
    stock: 12,
    slug: "architectural-tech-cargo-pants",
    tags: ["Technical", "Cargo", "Water-Repellent", "Techwear"],
    featured: true,
    category: "Pants",
    rating: 5.0,
    reviewsCount: 17,
    badge: "EXCLUSIVE"
  },
  {
    id: "prod-pants-satin-sapphire",
    name: "Satin Sapphire Utility Cargos",
    price: 155,
    sizes: ["S", "M", "L", "XL", "XXL"],
    images: ["/pants/Satin-Sapphire-Black-Cargo-Pants-1.webp"],
    description: "Heavy luxury sateen fabrics styled into structural pocket patterns, showing a subtle sapphire luster under bright lights.",
    colors: ["Sapphire Black", "Midnight Blue"],
    stock: 14,
    slug: "satin-sapphire-utility-cargos",
    tags: ["Satin", "Cargo", "Luxury", "Deep-Blue"],
    featured: false,
    category: "Pants",
    rating: 4.9,
    reviewsCount: 22,
    badge: "LIMITED"
  },
  {
    id: "prod-pants-xl-baggy",
    name: "Elsewhere XL Baggy Jeans",
    price: 130,
    sizes: ["S", "M", "L", "XL", "XXL"],
    images: ["/pants/ab-xl-baggy-jean-salle-blue-front-10005714.webp"],
    description: "Extreme volume silhouette inspired by late 90s skateboard wear, crafted in tough-wear heavyweight blue denim fabric.",
    colors: ["Salle Blue", "Light Wash Blue"],
    stock: 40,
    slug: "elsewhere-xl-baggy-jeans",
    tags: ["Baggy", "Jeans", "Denim", "Streetwear"],
    featured: true,
    category: "Pants",
    rating: 4.8,
    reviewsCount: 35
  },
  {
    id: "prod-pants-pleated-dress",
    name: "Classic Pleated Dress Trousers",
    price: 128,
    sizes: ["S", "M", "L", "XL", "XXL"],
    images: ["/pants/c2ea33c988a84ee38a0af1bc14ab8d1e.webp"],
    description: "Impeccably pressed pleats paired with high-quality stretch wool fabrics, designed for a modern transition from high-end corporate to cozy streetwear.",
    colors: ["Charcoal Grey", "Coal Black"],
    stock: 16,
    slug: "classic-pleated-dress-trousers",
    tags: ["Pleated", "Dress-Trouser", "Smart", "Tailored"],
    featured: false,
    category: "Pants",
    rating: 4.4,
    reviewsCount: 18
  },
  {
    id: "prod-pants-active-track",
    name: "Active Training Track Pants",
    price: 95,
    sizes: ["S", "M", "L", "XL", "XXL"],
    images: ["/pants/w=1200,h=1400,fit=cover.webp"],
    description: "Optimized for extreme daily active drills and street tracking. Lightweight, stretchy dynamic fabrics with seamless back zipper details.",
    colors: ["Tech Grey", "Pitch Black"],
    stock: 30,
    slug: "active-training-track-pants",
    tags: ["Activewear", "Track", "Training", "Minimalist"],
    featured: false,
    category: "Pants",
    rating: 4.6,
    reviewsCount: 12
  },
  {
    id: "prod-sneaker-canvas-classic",
    name: "Elsewhere Classic Canvas Sneaker",
    price: 120,
    sizes: ["S", "M", "L", "XL", "XXL"],
    images: ["/sneakers/108074f06c6ed5125d22c969861e1c39.jpg_960x960q80.jpg_.webp"],
    description: "A classic, minimalist silhouette with sturdy canvas panel construction, matching rubber toe caps, and all-day cupsole support.",
    colors: ["Off-White", "Cream"],
    stock: 25,
    slug: "elsewhere-classic-canvas-sneakers",
    tags: ["Classic", "Canvas", "Minimalist", "Everyday"],
    featured: true,
    category: "Sneakers",
    rating: 4.8,
    reviewsCount: 34,
    badge: "NEW IN"
  },
  {
    id: "prod-sneaker-retro-court",
    name: "Elsewhere Retro Court Trainer",
    price: 135,
    sizes: ["S", "M", "L", "XL", "XXL"],
    images: ["/sneakers/13a4910a-a9a6-41ec-b58e-0571eeafeb2f.webp"],
    description: "Classic court trainer with retro color accents, low-profile collar padding, and high-traction rubber outsole.",
    colors: ["White/Green", "White/Black"],
    stock: 18,
    slug: "elsewhere-retro-court-trainers",
    tags: ["Retro", "Court", "Classic", "Leather"],
    featured: false,
    category: "Sneakers",
    rating: 4.7,
    reviewsCount: 22,
    badge: "TRENDING"
  },
  {
    id: "prod-sneaker-shadow-tech",
    name: "Elsewhere Shadow Tech Runner",
    price: 155,
    sizes: ["S", "M", "L", "XL", "XXL"],
    images: ["/sneakers/1_org_zoom.webp"],
    description: "Technical running shoes featuring lightweight breathable mesh, dynamic cushioned midsole, and structured thermoplastic heel stability clips.",
    colors: ["Triple Black", "Gunmetal Grey"],
    stock: 22,
    slug: "elsewhere-shadow-tech-runners",
    tags: ["Technical", "Runner", "Activewear", "Mesh"],
    featured: true,
    category: "Sneakers",
    rating: 4.9,
    reviewsCount: 45,
    badge: "HYPED"
  },
  {
    id: "prod-sneaker-urban-platform",
    name: "Elsewhere Urban Platform Sneaker",
    price: 165,
    sizes: ["S", "M", "L", "XL", "XXL"],
    images: ["/sneakers/4bdde44ed7e247c5b893b646cf798301.webp"],
    description: "A modern chunky platform design combining split-suede overlays, technical knit underlays, and custom grooved traction sole structures.",
    colors: ["Sand Beige", "Warm Alabaster"],
    stock: 14,
    slug: "elsewhere-urban-platform-sneakers",
    tags: ["Chunky", "Platform", "Suede", "Urban"],
    featured: false,
    category: "Sneakers",
    rating: 4.6,
    reviewsCount: 19,
    badge: "BEST SELLER"
  },
  {
    id: "prod-sneaker-red-tape",
    name: "Red Tape Classic Sport Trainer",
    price: 95,
    originalPrice: 120,
    sizes: ["S", "M", "L", "XL"],
    images: ["/sneakers/7-rsl099-red-tape-black-white-original-imah4mfzqchaygph.webp"],
    description: "Sporty low-top sneakers featuring classic side stripes and lightweight EVA outsoles for versatile everyday athletic style.",
    colors: ["Black/White", "Grey/Black"],
    stock: 45,
    slug: "red-tape-classic-sport-trainers",
    tags: ["Sporty", "Low-top", "Red-Tape", "Everyday"],
    featured: false,
    category: "Sneakers",
    rating: 4.5,
    reviewsCount: 61
  },
  {
    id: "prod-sneaker-aurora-court",
    name: "Aurora Premium Leather Trainer",
    price: 180,
    sizes: ["S", "M", "L", "XL", "XXL"],
    images: ["/sneakers/AURORA_IB1667-101_PHSRH000-2000.webp"],
    description: "Sophisticated full-grain premium leather trainer with elegant contrast stitching, calfskin lining, and handcrafted vulc sole finishings.",
    colors: ["Chalk White", "Vintage Ivory"],
    stock: 12,
    slug: "aurora-premium-leather-trainers",
    tags: ["Premium", "Leather", "Luxury", "Chalk-White"],
    featured: true,
    category: "Sneakers",
    rating: 5.0,
    reviewsCount: 15,
    badge: "PREMIUM"
  },
  {
    id: "prod-sneaker-gclass-runner",
    name: "G-Class Urban Retro Runner",
    price: 145,
    sizes: ["S", "M", "L", "XL", "XXL"],
    images: ["/sneakers/G6107_0256_main5.jpg"],
    description: "A heritage runner silhouette with premium nubuck overlays, high-density foam cushioning, and iconic multi-terrain grip.",
    colors: ["Silver Grey", "Coal Black"],
    stock: 20,
    slug: "gclass-urban-retro-runners",
    tags: ["Heritage", "Runner", "Nubuck", "Grey"],
    featured: false,
    category: "Sneakers",
    rating: 4.7,
    reviewsCount: 28
  },
  {
    id: "prod-sneaker-nike-p6000",
    name: "Nike P-6000 Metallic Silver",
    price: 175,
    sizes: ["S", "M", "L", "XL", "XXL"],
    images: ["/sneakers/Nike-P-6000-Metallic-Silver-2025-argentee-et-brillante-CN0149-001-couv.jpg"],
    description: "A blast from the running past with breathable metallic mesh overlays and early 2000s athletic design features for high-end modern streetwear.",
    colors: ["Metallic Silver/White", "Metallic Gold/Black"],
    stock: 16,
    slug: "nike-p6000-metallic-silver-2025",
    tags: ["Nike", "Metallic", "Y2K", "Athletic"],
    featured: true,
    category: "Sneakers",
    rating: 4.9,
    reviewsCount: 42,
    badge: "EXCLUSIVE"
  },
  {
    id: "prod-sneaker-ss26-minimal",
    name: "Elsewhere SS26 Minimal Low-Top",
    price: 190,
    sizes: ["S", "M", "L", "XL", "XXL"],
    images: ["/sneakers/ss26-men-sneakers-low.jpg"],
    description: "A masterpiece of modern minimal shoetry featuring raw edges, cream matte finishing, organic cotton laces, and structured leather footbeds.",
    colors: ["Oatmeal Cream", "Chalk White"],
    stock: 10,
    slug: "elsewhere-ss26-minimal-lowtops",
    tags: ["Minimalist", "SS26", "Low-top", "Oatmeal"],
    featured: true,
    category: "Sneakers",
    rating: 5.0,
    reviewsCount: 11,
    badge: "LIMITED"
  }
];

export const CATEGORIES = ["All", "Hoodies", "T-shirts", "Pants", "Sneakers"];
